export interface SonItem {
  title: string;
  icon: string;
  router: string;
  sonId:Number;
  fatherId:Number;
}

export interface NewMenuList {
  title: string;
  icon: string;
  fatherId:Number;
  sonList:Array<SonItem>
}

export interface MenuParams {
  openNames:string
  activeName:string
}


export let newMenuList:Array<T>= [
    {
        title:"资源总揽",
        icon:"md-desktop",
        fatherId:1,
        sonList:[
          {
            title:"首页",
            icon:"ios-paper",
            fatherId:1,
            sonId:0,
            router:"/home",
          },
        ]
      },
      {
        title:"业务系统管理",
        icon:"ios-keypad",
        fatherId:2,
        sonList:[
          {
            title:"业务清单",
            icon:"md-list-box",
            fatherId:2,
            sonId:0,
            router:"/articleList",
          },
        ]
      },
       {
        title:"云主机管理",
        icon:"md-phone-landscape",
        fatherId:3,
        sonList:[
          {
            title:"网络部",
            icon:"md-list-box",
            fatherId:3,
            sonId:0,
            router:"/videoList",
          },
          {
            title:"信技部",
            icon:"md-list-box",
            sonId:1,
            fatherId:3,
            router:"",
          },
          {
            title:"采购部",
            icon:"md-list-box",
            sonId:2,
            fatherId:3,
            router:"",
          },
          {
            title:"办公室",
            icon:"md-list-box",
            sonId:3,
            fatherId:3,
            router:"",
          },
          {
            title:"其它部门",
            icon:"md-list-box",
            sonId:4,
            router:"",
            fatherId:3,
          },
        ]
      },
      {
        title:"硬件资产管理",
        icon:"ios-create",
        fatherId:4,
        sonList:[]
      },
      {
        title:"下架设备管理",
        icon:"ios-create",
        fatherId:5,
        sonList:[]
      },
      {
        title:"借出清单管理",
        icon:"ios-create",
        fatherId:6,
        sonList:[]
      },
      {
        title:"备件库管理",
        icon:"ios-create",
        fatherId:7,
        sonList:[]
      },
       {
        title:"用户管理",
        icon:"ios-person",
        fatherId:8,
        sonList:[]
      },
      {
        title:"系统管理",
        icon:"ios-settings",
        fatherId:9,
        sonList:[]
      },
       {
        title:"留言管理",
        icon:"ios-chatboxes",
        fatherId:10,
        sonList:[]
      },
      {
        title:"集采管理",
        icon:"ios-megaphone",
        fatherId:11,
        sonList:[]
      },
    ]